TNA_LEVELS = {
    "1": "Department",
    "2": "Division",
    "3": "Series",
    "4": "Sub-series",
    "5": "Sub-sub-series",
    "6": "Piece",
    "7": "Item",
}

NON_TNA_LEVELS = {
    "1": "Fonds",
    "2": "Sub-fonds",
    "3": "Sub-sub-fonds",
    "4": "Sub-sub-sub-fonds",
    "5": "Series",
    "6": "Sub-series",
    "7": "Sub-sub-series",
    "8": "Sub-sub-sub-series",
    "9": "File",
    "10": "Item",
    "11": "Sub-item",
}

CLOSURE_STATUSES = {
    "1": "Closed Or Retained Document, Closed Description",
    "2": "Closed Or Retained Document, Open Description",
    "3": "Open Document, Open Description",
}

COLLECTIONS = {
    "1": "WO - War Office, Armed Forces, Judge Advocate General, and related bodies",
    "2": "BT - Board of Trade and successors",
}

TNA_SUBJECTS = {
    "0": "Armed Forces (General Administration)",
    "1": "Army",
    "2": "Operations, battles and campaigns",
    "3": "Conflict",
    "4": "Medals",
    "5": "Navy",
    "6": "Trade and commerce",
    "7": "Europe and Russia",
    "8": "Litigation",
    "9": "International",
    "10": "Food and drink",
    "11": "Nursing",
    "12": "Nationality",
    "13": "Wills and probate",
    "14": "Indian Subcontinent",
    "15": "Migration",
    "16": "Merchant seaman",
    "17": "Air Force",
    "18": "Art, architecture and design",
    "19": "Maps and plans",
    "20": "Taxation",
    "21": "Weapons",
    "22": "Sex and gender",
    "23": "Africa",
    "24": "Asia",
    "25": "Middle East",
    "26": "Railways",
    "27": "Marriage and divorce",
    "28": "Research",
    "29": "Americas",
    "30": "Internment",
    "31": "Shipping",
    "32": "Pay and pensions",
    "33": "Religions",
    "34": "Farming",
    "35": "Labour",
    "36": "Local Government",
    "37": "Education",
    "38": "Government finances",
    "39": "Census",
    "40": "Caribbean",
    "41": "Official publications",
    "42": "Communications",
    "43": "Children",
    "44": "Crime",
    "45": "Coal",
    "46": "Manors",
    "47": "Ireland",
    "48": "Mining and quarrying",
    "49": "Fishing",
    "50": "Intelligence",
    "51": "Transport management",
    "52": "Welfare",
    "53": "Manufacturing",
    "54": "Personal and family papers",
    "55": "Landed estates",
    "56": "Diaries",
    "57": "Legal",
    "58": "Archives and libraries",
    "59": "Debt",
    "60": "Poverty",
    "61": "Australia and Pacific",
    "62": "Nuclear energy",
    "63": "Crown lands and estates",
    "64": "Conveyancing",
    "65": "Oil and gas",
    "66": "Tithes",
    "67": "Banking",
    "68": "Policing",
    "69": "Treaties and alliances",
    "70": "Forestry",
    "71": "Clothing",
    "72": "Air transport",
    "73": "Planning (Land and Property)",
    "74": "Construction industries",
    "75": "Aid and development",
    "76": "Prisons",
    "77": "Medicine",
    "78": "Road transport",
    "79": "Disease",
    "80": "Democracy",
    "81": "Population",
    "82": "Sports",
    "83": "Canals and river transport",
    "84": "Housing",
    "85": "Radio and television",
    "86": "Events and exhibitions",
    "87": "Refugees",
    "88": "Pardons",
    "89": "Photography and film",
    "90": "Iron, steel and metals",
    "91": "Friendly societies",
    "92": "Disasters and emergencies",
    "93": "Ancient Monuments and Historical Buildings",
    "94": "Resources",
    "95": "Transportation",
    "96": "National Health Service",
    "97": "Mental illness",
    "98": "Sewerage",
    "99": "Disarmament",
}
