TNA_LEVELS = {
    "1": "Department",
    "2": "Division",
    "3": "Series",
    "4": "Sub-series",
    "5": "Sub-sub-series",
    "6": "Piece",
    "7": "Item",
}

NON_TNA_LEVELS = {
    "1": "Fonds",
    "2": "Sub-fonds",
    "3": "Sub-sub-fonds",
    "4": "Sub-sub-sub-fonds",
    "5": "Series",
    "6": "Sub-series",
    "7": "Sub-sub-series",
    "8": "Sub-sub-sub-series",
    "9": "File",
    "10": "Item",
    "11": "Sub-item",
}

CLOSURE_STATUSES = {
    "1": "Closed Or Retained Document, Closed Description",
    "2": "Closed Or Retained Document, Open Description",
    "3": "Open Document, Open Description",
}

COLLECTIONS = {
    "1": "WO - War Office, Armed Forces, Judge Advocate General, and related bodies",
    "2": "BT - Board of Trade and successors",
}

TNA_SUBJECTS = {
    "1": "Armed Forces (General Administration)",
    "2": "Army",
    "3": "Operations, battles and campaigns",
    "4": "Conflict",
    "5": "Medals",
    "6": "Navy",
    "7": "Trade and commerce",
    "8": "Europe and Russia",
    "9": "Litigation",
    "10": "International",
    "11": "Food and drink",
    "12": "Nursing",
    "13": "Nationality",
    "14": "Wills and probate",
    "15": "Indian Subcontinent",
    "16": "Migration",
    "17": "Merchant seaman",
    "18": "Air Force",
    "19": "Art, architecture and design",
    "20": "Maps and plans",
    "21": "Taxation",
    "22": "Weapons",
    "23": "Sex and gender",
    "24": "Africa",
    "25": "Asia",
    "26": "Middle East",
    "27": "Railways",
    "28": "Marriage and divorce",
    "29": "Research",
    "30": "Americas",
    "31": "Internment",
    "32": "Shipping",
    "33": "Pay and pensions",
    "34": "Religions",
    "35": "Farming",
    "36": "Labour",
    "37": "Local Government",
    "38": "Education",
    "39": "Government finances",
    "40": "Census",
    "41": "Caribbean",
    "42": "Official publications",
    "43": "Communications",
    "44": "Children",
    "45": "Crime",
    "46": "Coal",
    "47": "Manors",
    "48": "Ireland",
    "49": "Mining and quarrying",
    "50": "Fishing",
    "51": "Intelligence",
    "52": "Transport management",
    "53": "Welfare",
    "54": "Manufacturing",
    "55": "Personal and family papers",
    "56": "Landed estates",
    "57": "Diaries",
    "58": "Legal",
    "59": "Archives and libraries",
    "60": "Debt",
    "61": "Poverty",
    "62": "Australia and Pacific",
    "63": "Nuclear energy",
    "64": "Crown lands and estates",
    "65": "Conveyancing",
    "66": "Oil and gas",
    "67": "Tithes",
    "68": "Banking",
    "69": "Policing",
    "70": "Treaties and alliances",
    "71": "Forestry",
    "72": "Clothing",
    "73": "Air transport",
    "74": "Planning (Land and Property)",
    "75": "Construction industries",
    "76": "Aid and development",
    "77": "Prisons",
    "78": "Medicine",
    "79": "Road transport",
    "80": "Disease",
    "81": "Democracy",
    "82": "Population",
    "83": "Sports",
    "84": "Canals and river transport",
    "85": "Housing",
    "86": "Radio and television",
    "87": "Events and exhibitions",
    "88": "Refugees",
    "89": "Pardons",
    "90": "Photography and film",
    "91": "Iron, steel and metals",
    "92": "Friendly societies",
    "93": "Disasters and emergencies",
    "94": "Ancient Monuments and Historical Buildings",
    "95": "Resources",
    "96": "Transportation",
    "97": "National Health Service",
    "98": "Mental illness",
    "99": "Sewerage",
    "100": "Disarmament",
}

SUBJECTS_LIMIT = 20
